"""Emit a TikZ figure of the between-partition shared-neighbours analysis
for direct \\input{} into the paper. Pure text + arrows, no boxes.

For each resolution: anchor A on the left, between-partition cells stacked
vertically in the middle, anchor B on the right. Arrows fan from anchor A
to each middle cell and from each middle cell to anchor B. Resolutions
stacked vertically.

Anchor IDs at each resolution come from the JSON's per_resolution.anchor_*_pid.
When the upstream experiment ran with --identity-track, those IDs reference
the same first-arrival activation across dictionaries (the partition's
exemplar_direction is identical at every resolution); without it, they are
nearest-direction projections that may drift across resolutions.

Usage:
    uv run python -m scripts.make_fig_shared_lens_tikz \\
        --geom-root /tmp/ep_check/resolution_paths_geom/exemplar \\
        --paths-json /tmp/ep_check/resolution_paths_identity/resolution_paths.json \\
        --pair-index 0 --resolutions p16,p10,p8 \\
        --output paper/figures/shared_lens_cognition.tex \\
        --display-cap 8
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


_LATEX_ESCAPES = {
    "\\": "\\textbackslash{}", "&": "\\&", "%": "\\%", "$": "\\$",
    "#": "\\#", "_": "\\_", "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}",
    "^": "\\textasciicircum{}",
}


def _latex_escape(s: str) -> str:
    out = []
    for c in s:
        out.append(_LATEX_ESCAPES.get(c, c))
    return "".join(out)


def _is_latin(t: str) -> bool:
    """True if every char in t is in the Latin-1 ASCII subset (printable).
    Tokens containing non-Latin scripts are skipped so the TikZ output
    compiles cleanly under pdflatex without Unicode font setup."""
    return all(ord(c) < 128 for c in t)


def _is_displayable(t: str) -> bool:
    """Drop tokens whose content is pure punctuation/symbols of length > 1
    (e.g. ``"]),`` ``'));,`` ``\"});``) since these read as noise rather than
    decoded content. Keep single-char punctuation (``.``, ``,``) since the
    model genuinely activates on them and they belong in the decode."""
    if len(t) == 1:
        return True
    return any(c.isalnum() for c in t)


def _short_tokens(decode: str, n: int = 8, char_limit: int = 64) -> str:
    seen: list[str] = []
    for t in decode.split(","):
        t = t.strip()
        if not t or t in seen or not _is_latin(t) or not _is_displayable(t):
            continue
        seen.append(t)
        if len(seen) >= n:
            break
    s = ", ".join(seen)
    if len(s) > char_limit:
        s = s[:char_limit - 1] + "\\ldots"
    return s


def _build_tikz(panel_data: list[dict], display_cap: int) -> str:
    """panel_data: list of {tag, K, d_ab, a_pid, a_dec, b_pid, b_dec,
                            lens_total, lens_show: [(pid, dec, sim_a, sim_b), ...]}"""
    PANEL_GAP = 1.6
    LENS_GAP = 0.55
    ANCHOR_X = 0.0
    LENS_X = 6.0
    ANCHOR_B_X = 12.0

    out: list[str] = []
    out.append("% Auto-generated by scripts.make_fig_shared_lens_tikz; do not edit by hand.")
    out.append("\\begin{tikzpicture}[")
    out.append("    every node/.style={font=\\small, inner sep=1.2pt},")
    out.append("    anchorcell/.style={align=center, font=\\footnotesize},")
    out.append("    middle/.style={align=center, font=\\footnotesize, text=black!70},")
    out.append("    pid/.style={font=\\scriptsize, color=black!50},")
    out.append("    head/.style={font=\\small\\bfseries},")
    out.append("    arrow/.style={-{Stealth[length=1.2mm]}, draw=black!35, line width=0.3pt},")
    out.append("    simlabel/.style={font=\\tiny, text=black!50, fill=white, inner sep=0.7pt},")
    out.append("]")

    y_cursor = 0.0
    for panel in panel_data:
        n_lens = len(panel["lens_show"])
        panel_h = max(1.4, LENS_GAP * (max(1, n_lens) - 1) + 0.6)
        panel_top = y_cursor
        panel_centre = panel_top - panel_h / 2

        # Panel heading. The percentile gets math-mode subscript (e.g. $p_{10}$)
        # so it doesn't collide visually with partition IDs ("p92"), which stay
        # plain in node labels.
        pct_num = panel["tag"].lstrip("p").replace("p", ".")
        cos_ab = 1.0 - panel["d_ab"]
        n_shown = len(panel["lens_show"])
        if panel["lens_total"] > n_shown and n_shown > 0:
            shown_tag = (
                f" ({n_shown} content cells shown)"
                if panel.get("manual_select")
                else f" (closest {n_shown} shown)"
            )
        else:
            shown_tag = ""
        head_text = (f"$p_{{{pct_num}}}$  "
                     f"\\quad $K = {panel['K']}$ "
                     f"\\quad $\\cos(A, B) = {cos_ab:.3f}$ "
                     f"\\quad $|C| = {panel['lens_total']}$"
                     + shown_tag)
        head_y = panel_top + 0.55
        out.append(f"  \\node[head] (h{panel['tag']}) at ({(ANCHOR_X + ANCHOR_B_X) / 2:.2f}, {head_y:.2f}) "
                   f"{{{head_text}}};")

        # Anchor A. Region IDs rendered as bare numbers (matching paper
        # convention) so they don't collide visually with the $p_{N}$
        # percentile in the heading.
        out.append(f"  \\node[anchorcell] (a{panel['tag']}) at ({ANCHOR_X:.2f}, {panel_centre:.2f}) "
                   f"{{\\textbf{{region {panel['a_pid']}}} \\\\ {_latex_escape(panel['a_dec'])}}};")
        # Anchor B
        out.append(f"  \\node[anchorcell] (b{panel['tag']}) at ({ANCHOR_B_X:.2f}, {panel_centre:.2f}) "
                   f"{{\\textbf{{region {panel['b_pid']}}} \\\\ {_latex_escape(panel['b_dec'])}}};")

        # Lens cells
        if n_lens == 0:
            out.append(f"  \\node[middle] (l{panel['tag']}_empty) at "
                       f"({LENS_X:.2f}, {panel_centre:.2f}) "
                       f"{{\\textit{{(empty)}}}};")
            out.append(f"  \\draw[arrow, dashed] (a{panel['tag']}) -- (b{panel['tag']});")
        else:
            top = panel_centre + ((n_lens - 1) * LENS_GAP) / 2
            for i, lens_entry in enumerate(panel["lens_show"]):
                pid, dec, sim_a, sim_b = lens_entry
                y = top - i * LENS_GAP
                node_id = f"l{panel['tag']}_{i}"
                out.append(
                    f"  \\node[middle] ({node_id}) at ({LENS_X:.2f}, {y:.2f}) "
                    f"{{\\textcolor{{black!50}}{{\\scriptsize {pid}:}}~"
                    f"{_latex_escape(dec)}}};")
                out.append(
                    f"  \\draw[arrow] (a{panel['tag']}) -- node[simlabel, pos=0.55] "
                    f"{{{sim_a:.2f}}} ({node_id});")
                out.append(
                    f"  \\draw[arrow] ({node_id}) -- node[simlabel, pos=0.45] "
                    f"{{{sim_b:.2f}}} (b{panel['tag']});")

        y_cursor = panel_top - panel_h - PANEL_GAP

    out.append("\\end{tikzpicture}")
    return "\n".join(out) + "\n"


def _parse_cell_overrides(spec: str) -> dict[str, list[int]]:
    """Parse "tag:id,id,...;tag:id,..." into {tag: [ids]}.

    Used to hand-pick which lens cells appear at a given resolution when the
    auto-rank includes glyph-artefact / function-token cells the user wants
    suppressed in favour of content-coherent ones.
    """
    out: dict[str, list[int]] = {}
    if not spec:
        return out
    for chunk in spec.split(";"):
        chunk = chunk.strip()
        if not chunk:
            continue
        tag, ids = chunk.split(":", 1)
        out[tag.strip()] = [int(x) for x in ids.split(",") if x.strip()]
    return out


def _load_cell_displays(path: Path | None) -> dict[str, dict[int, str]]:
    """Load explicit per-cell display strings from JSON: ``{tag: {id: text}}``.

    Used when the auto _short_tokens output mixes CamelCase code identifiers
    or duplicate-cased tokens with the natural-language content the figure is
    meant to surface, and the right summary differs per cell. Display
    strings replace the auto top-N tokens for matching (tag, id) pairs;
    cells without an entry fall back to _short_tokens.
    """
    if not path:
        return {}
    raw = json.load(open(path))
    return {tag: {int(k): v for k, v in cells.items()} for tag, cells in raw.items()}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--geom-root", type=Path, required=True)
    ap.add_argument("--paths-json", type=Path, required=True)
    ap.add_argument("--pair-index", type=int, required=True)
    ap.add_argument("--resolutions", default="p10,p4,p2")
    ap.add_argument("--display-cap", type=int, default=8)
    ap.add_argument(
        "--cell-overrides", default="",
        help="Hand-pick lens cells to display per resolution. Format: "
             "'tag:id,id,...;tag:id,...'. Overrides auto top-N selection "
             "for the listed tags only. Cells not in the lens (failing the "
             "cosine criterion) are silently dropped with a warning.",
    )
    ap.add_argument(
        "--cell-displays", type=Path, default=None,
        help="Path to JSON {tag: {id: text}} mapping per-cell display "
             "strings. Replaces _short_tokens output for matching "
             "(tag, id) pairs.",
    )
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()

    res_tags = [t.strip() for t in args.resolutions.split(",") if t.strip()]
    overrides = _parse_cell_overrides(args.cell_overrides)
    displays = _load_cell_displays(args.cell_displays)
    d = json.load(open(args.paths_json))
    pair = d["pairs"][args.pair_index]
    res_by_tag = {r["tag"]: r for r in pair["per_resolution"]}

    panels: list[dict] = []
    for tag in res_tags:
        r = res_by_tag[tag]
        geom = np.load(args.geom_root / tag / "geom.npz")["geom"]
        tok = json.load(open(args.geom_root / tag / "top_tokens.json"))
        tok_by_pid = {t["partition_id"]: t["exemplar_top_tokens"] for t in tok}
        a, b = r["anchor_a_pid"], r["anchor_b_pid"]
        d_ab = float(geom[a, b])
        mask = (geom[a] < d_ab) & (geom[b] < d_ab)
        mask[a] = False
        mask[b] = False
        cells = sorted(np.flatnonzero(mask).tolist(),
                       key=lambda c: 0.5 * (geom[a, c] + geom[b, c]))
        lens_total = len(cells)
        if tag in overrides:
            in_lens = set(cells)
            picked = []
            for c in overrides[tag]:
                if c in in_lens:
                    picked.append(c)
                else:
                    print(
                        f"warning: {tag} override cell {c} not in lens; skipped",
                    )
            show = picked
            manual_select = True
        else:
            show = cells[: args.display_cap]
            manual_select = False
        panels.append({
            "manual_select": manual_select,
            "tag": tag,
            "K": int(r["K"]),
            "d_ab": d_ab,
            "a_pid": int(a),
            "a_dec": _short_tokens(tok_by_pid[a], n=4, char_limit=40),
            "b_pid": int(b),
            "b_dec": _short_tokens(tok_by_pid[b], n=4, char_limit=40),
            "lens_total": lens_total,
            "lens_show": [
                (int(c),
                 displays.get(tag, {}).get(int(c),
                                          _short_tokens(tok_by_pid[c], n=8, char_limit=72)),
                 float(1.0 - geom[a, c]),     # cos(A, C)
                 float(1.0 - geom[b, c]))     # cos(B, C)
                for c in show
            ],
        })

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(_build_tikz(panels, display_cap=args.display_cap))
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
